### ISSUE TITLE
Nexe does not automatically bundle dependencies

### ISSUE THREAD

**Issue by garbados** [nexe/nexe#642]
**Is this a BUG or a FEATURE REQUEST?:** 

Bug :bug: :beetle: :bee: 

**What happened:**

The produced binaries fail to run unless the entirety of `node_modules/` is bundled with them. If `node_modules/` is moved or removed, the binary complains that it cannot find necessary modules.

```bash
$ npm i
$ npx nexe -i ./bin/agent -t static-x64-10.15.0 -o build/agent -r lib/
$ rm -rf node_modules/
$ ./build/agent --help
Error: Cannot find module 'yargs'
```

The workaround, to specify `-r node_modules/` doubles the size of the resulting executables, creating 100MB binaries from 29KB of source code.

**What you expected to happen:**

I expect Nexe to resolve `require` calls during compilation, and not to fail for want of dependencies after the fact.

**How to reproduce it (as minimally and precisely as possible):**

See the above code sample.

**Anything else we need to know?:**

**Environment**

- Platform(OS/Version): Ubuntu 18.04
- Host Node Version: v10.7.0
- Target Node Version: v10.15.0
- Nexe version: v3.3.1
- Python Version: 2.7.15+ / 3.7.0

**Comment by calebboyd** [comment]
Thanks for reporting!

**Comment by garbados** [comment]
No problem. Let me know if there's anything I can do to help :)

**Comment by calebboyd** [comment]
Can you post the output from `DEBUG=nexe:requre ./build/agent`

**Comment by garbados** [comment]
Sure thing. I've loaded the result of that invocation into this gist: https://gist.github.com/garbados/ac0dee9c5b647342a7a632da01722d8b

**Comment by calebboyd** [comment]
What do you get for `npm ls yargs`

**Comment by garbados** [comment]
Before removing `node_modules/`:

```bash
$ npm ls yargs
$PROJECT@$VERSION /home/$USER/code/$PROJECT
└── yargs@12.0.5 
```

After removing `node_modules/`:

```bash
$ npm ls yargs
$PROJECT@$VERSION /home/$USER/code/$PROJECT
└── UNMET DEPENDENCY yargs@12.0.5 

npm ERR! missing: yargs@12.0.5, required by $PROJECT@$VERSION
```

**Comment by calebboyd** [comment]
I'm having trouble replicating the issue. Are you explicitly requiring yargs?

test.js

```
console.log(require('yargs'))
```

`nexe test.js -o ~/Desktop/out`

**Comment by garbados** [comment]
Yes, yargs gets explicitly required. Line 9 of the entry file, `bin/agent`:

```javascript
const yargs = require('yargs')
```

**Comment by calebboyd** [comment]
Hmm interesting.

What package manager are you using? 
What install command?
What does your package.json (dependencies) look like?

**Comment by garbados** [comment]
I hesitate to link the project's dependencies but I will say yargs is in there:

```bash
$ cat package.json | jq .dependencies.yargs
"^12.0.5"
```

**Comment by garbados** [comment]
FWIW, when I move the entry script from a nested directory (ex: `bin/`) to a file at the project's top level (ex: `bin.js`) nexe correctly bundles the required files so that removing `node_modules/` does not break the executable. This leads me to believe there's something of a pathing problem regarding the entry file when it's nested places.

**Comment by calebboyd** [comment]
Any way you could come up with a minimal reproduction? I am unable to replicate the issue (using the paths specified)..

**Comment by garbados** [comment]
Yeah, I just put together an isolated test case. Lemme write up the repro steps...

**Comment by garbados** [comment]
OK, here's bash instructions:

```bash
$ npm init
$ mkdir bin
$ echo "console.log(require('yargs'))" > bin/entry
$ npm i -S yargs
$ npx nexe -i bin/entry -t linux-x64 -o entry-exe
$ ./entry-exe
{ [Function: Argv] ...
$ rm -rf node_modules
$ ./entry-exe
Error: Cannot find module 'yargs'
# that shows nexe isn't bundling dependencies
# but if we move the entry file to the top level, it works
$ npm i
$ cp bin/entry entry.js
$ npx nexe -i entry.js -t linux-x64 -o entry-exe
$ rm -rf node_modules/
$ ./entry-exe
{ [Function: Argv] ...
```

Does that help?

**Comment by cah-calebboyd** [comment]
`mv bin/entry bin/entry.js`

should fix it I think

**Comment by calebboyd** [comment]
`mv bin/entry bin/entry.js`

should fix it I think

**Comment by garbados** [comment]
> Dependency collection currently relies on the file type being derivable from the extension.

Ah, that's the missing piece then -- the extension, not the path itself. That fixes the problem on our end, so I'll go ahead and close this issue. Thanks!

**Comment by vmarchaud** [comment]
I've got the same issue using the last version, switching to a `.js` extension doesn't fix the issue for me through, i get the following error:
```
Error: Error: EACCES: permission denied, scandir '/lib/ssl/private'
```
I understand that the module `resolve-dependencies` is looking for them but why is it going on the root of my FS ? Do you have an idea @calebboyd ? Thanks for your help
