### ISSUE TITLE
Error: make  exited with code: 2 

### ISSUE THREAD

**Issue by JayyWalker** [nexe/nexe#804]
**What happened**:
I ran `yarn nexe -i build/app.js -o dist/nerm.js --build` and received `Error: make  exited with code: 2`. 

Here is the output when the command is ran with the `--verbose` option: [pastebin url](https://pastebin.com/A2LnZeq6). I've replaced my home path with `<HOME_PATH>` throughout.

**What you expected to happen**:
I expected my code to be built into a binary

**How to reproduce it (as minimally and precisely as possible)**:
I ran `yarn nexe -i build/app.js -o dist/nerm.js --build`. 

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version): Mac OS Catalina 10.15.4
- Host Node Version: 12.18.3
- Target Node Version: 12.18.3
- Nexe version: 3.3.7
- Python Version: Python 2.7.16

**Comment by robinmollah** [comment]
Same issue:
Platform(OS/Version): Mac OS Catalina 10.15.7
Host Node Version: 12.18.3
Target Node Version: 12.18.3
Nexe version: 3.3.7
Python Version: Python 2.7.16

**Comment by alchristleo** [comment]
Same issue:
Platform(OS/Version): Mac OS Catalina 10.15.4
Host Node Version: 12.18.3
Target Node Version: 12.18.3
Nexe version: 3.3.7
Python Version: Python 3.7.2

**Comment by Ayzrian** [comment]
It looks like bad code in `node.cc` 

> ../src/node.cc:771:66: error: extraneous ')' before ';'
>../src/node.cc:771:66: error: extraneous ')' before ';'

**Comment by Devalo** [comment]
Same issue here as well. Same versions as the ones above

**Comment by bnbowman** [comment]
Same issue as well, also on Mac

**Comment by jmls** [comment]
I just hit this, on ubuntu 20.10

**Comment by kiobu** [comment]
Also appearing on my Manjaro 5.9.11-3 install.

**Comment by calebboyd** [comment]
Should be fixed with latest beta/next npm tags

**Comment by halmos** [comment]
I'm still getting this with v4.0.0-beta.15 on OS X, node v15.4

**Comment by halmos** [comment]
NM. as it turns out the `--verbose` flag revealed the issue to be with OSX's x-code `make` throwing an unrelated error.
